### ISSUE TITLE
Sigle dataset import

### ISSUE THREAD

**Issue by giuliacmpl** [MoultDB/taxonbridge#1]
I see that functions for importing (load_sample(), load_taxonomy(), load_population() ) all require that you already have both NCBI and GBIF data. To make the package of interest for the biggest number of users possible, I think a common user scenario could be as follows:

one could have a sigle dataset (for example, a dataframe with species names in one column and the corresponding order, class, subphylum and so on in other columns) and be interested in comparing this data to GBIF. It would be nice for the user to not download by himself the GBIF data, but to normally importing his NCBI data in R and then apply a function that retrieve the entire GBIF dataset and internally filter them according to the NCBI queries from the user. In other words, giving a table with NCBI data as input, the output could be the same table with merged NCBI, GBIF data and then it can be used comparably to the input tables for the load_() methods already present in the package, to run downstream functions.

If this is already possible, maybe the README or the manual can explain this case scenario more explicitly.
Cheers!

**Comment by vrechdelaval** [comment]
@giuliacmpl I agree that it would be easier for the user not to have to download the data themselves.
But as @Werner0 told to me, the R environment times out after five minutes. This timeout can be set but to do this on behalf of the user would be a violation of CRAN policy.

From my point of view, the most "complicated" task is to download the NCBI data which requires an installation of the taxonkit tool and NCBI file is the lighter file of the two. So, in the proposed scenario, it would be nice for the user to not download by himself the NCBI data and the input would be GBIF data.

Just to give a notion of the amount of data size and download time (from my home but it depends on the network):
- to download the NCBI data (55M) it took less than a minute;
- to download the GBIF data (841M) it took almost 3 minutes.

**Comment by marcrr** [comment]
Hi, after discussion with @vrechdelaval and Julien W, the solution of implementing the download with a clear error message in case of timeout seems like a good compromise.

**Comment by Werner0** [comment]
I see the `options()` method can be used with caution as explained [here](https://r-pkgs.org/r.html). So we could temporarily change the timeout in global options using the [withr](https://search.r-project.org/CRAN/refmans/withr/html/with_options.html) package.

**Comment by Werner0** [comment]
Try out the new `download_ncbi()` and `download_gbif()` methods in the development version:

```
install.packages(c("devtools", "rmarkdown"))
devtools::install_github("MoultDB/taxonbridge", build_vignettes = TRUE)
library(taxonbridge)
```
