### ISSUE TITLE
Missing species

### ISSUE THREAD

**Issue by vrechdelaval** [MoultDB/taxonbridge#2]
It would be nice to have following species after the usage of Taxonbridge? Maybe some species are not found due to typos.
 
- Alacaris mirabilis
- Alalcomenaeus sp.
- Antarctidromia infalta
- Arthricocephalites xinzhaiheensis
- Brezelina palmata
- Burlingia balangensis
- Cambropycnogon klausmuelleri
- Cheliferidae indet.
- Cryptophyllus socialis
- Cytherella bullata
- Dalmanitina proaeva elfrida
- Eccaparadoxides sp. 
- Euproops sp.
- Hoploparia stokesi
- Marrella splendens
- Ogmoopsis bocki
- Paradoxidid sp.
- Protoryctocephalus arcticus
- Scyllarid sp.

**Comment by marcrr** [comment]
Note: with 'indet.' or 'sp.' the first term can be used alone, then they should be recovered correctly.

e.g. https://www.gbif.org/search?q=Cheliferidae

**Comment by Werner0** [comment]
Try the new `fuzzy_search()` method available in the development version of `taxonbridge`:

Start by downloading and loading the example [population file](https://drive.google.com/file/d/1gpvm9QKdOcuGo_cIXPkAgGlB-qfKZZU6/view?usp=sharing).

`pop <- load_population("/path/to/population.tsv.gz")`

Then use the loaded dataset as follow:

**EXAMPLE 1:**

`fuzzy_search(pop, "Alacaris mirabilis", sensitivity = 2)`

>Fuzzy search may be slower than expected...
>Candidate match(es) made on: Alacaris mirabilis
>[1] "Steganacarus mirabilis" "Paulianacris mirabilis"

**EXAMPLE 2:**

`fuzzy_search(pop, "Alalcomenaeus sp.", allow_term_removal = TRUE)`

>NOTE: Fuzzy search may be slower than expected...
>Candidate match(es) made by term removal on: Alalcomenaeus sp.
>[1] "Alalcomenaeus illecebrosus" "Alalcomenaeus"

**Comment by vrechdelaval** [comment]
The new method resolves the issue of 'sp.' and 'indet.' but this does not resolve missing species such as 'Cryptophyllus socialis' which is not in GBIF or in NCBI.

**Comment by vrechdelaval** [comment]
These species comes from the fossil annotation file (MBD2 file).

**Comment by Werner0** [comment]
That is not a database. If you have specific databases that you would like to see integrated in `taxonbridge`, I suggest you create a separate issue for that, or reopen [issue #3](https://github.com/MoultDB/taxonbridge/issues/3).
