### ISSUE TITLE
better way to call `TaxonKit reformat`

### ISSUE THREAD

**Issue by shenwei356** [MoultDB/taxonbridge#7]
Hi, thanks for using TaxonKit in this tool.

Since v0.8.0, `taxonkit reformat` supports input of TaxIds, which is [more robust](https://github.com/shenwei356/taxonkit/issues/42) than parsing taxon names. So [the commands](https://github.com/MoultDB/taxonbridge/blob/5790f4860703d3b150d1292c4ccf26bfaa84c29a/R/load_methods.R#L158)

```
taxonkit list --ids 1 \
    | taxonkit lineage --show-lineage-taxids --show-lineage-ranks --show-rank --show-name --data-dir=path/to/downloaded/files \
    | taxonkit reformat --data-dir=path/to/downloaded/files \
    > All.lineages.tsv
```

could be replaced with

```
taxonkit list --ids 1 \
    | taxonkit lineage --show-lineage-taxids --show-lineage-ranks --show-rank --show-name --data-dir=path/to/downloaded/files \
    | taxonkit reformat --taxid-field 1 --data-dir=path/to/downloaded/files \
    > All.lineages.tsv
```

Besides, outputting a gzip-compressed file could save some space (1.4GB).

```
taxonkit list --ids 1 \
    | taxonkit lineage --show-lineage-taxids --show-lineage-ranks --show-rank --show-name --data-dir=path/to/downloaded/files \
    | taxonkit reformat --taxid-field 1 --data-dir=path/to/downloaded/files -o All.lineages.tsv.gz
```

Wei

**Comment by Werner0** [comment]
Thank you, Wei. These suggestions will be implemented in the next version.

**Comment by shenwei356** [comment]
Please feel free to close this issue :)
